const fs = require('fs');
let c = fs.readFileSync('prisma/seed.ts', 'utf8');

// Extract all string literals and replace French content
// Strategy: replace line by line for any line still containing French indicators

const lines = c.split('\n');
const out = [];

const frToEn = [
  ['Politique de Sécurité de l'Information de DEKRA Maroc', 'DEKRA Maroc Information Security Policy'],
  ['Politique de Contrôle d'Accès', 'Access Control Policy'],
  ['Politique de Sauvegarde et de Restauration', 'Backup and Recovery Policy'],
  ['Politique de Gestion des Incidents de Sécurité', 'Security Incident Management Policy'],
  ['Politique de Continuité d'Activité', 'Business Continuity Policy'],
  ['Politique d'Utilisation Acceptable des Ressources IT', 'Acceptable Use of IT Resources Policy'],
  ['Politique de Gestion des Fournisseurs', 'Vendor Management Policy'],
  ['Politique de Classification de l'Information', 'Information Classification Policy'],
  ['Politique de Gestion des Vulnérabilités', 'Vulnerability Management Policy'],
  ['Politique de Télétravail et Accès Distant', 'Remote Work and Remote Access Policy'],
  ['Politique de Cryptographie', 'Cryptography Policy'],
  ['Politique de Sécurité Physique', 'Physical Security Policy'],
  ['Politique de développement sécurisé', 'Secure Development Policy'],
  ['Politique de gestion des changements', 'Change Management Policy'],
  ['Charte Informatique', 'IT Acceptable Use Charter'],
  ['Politique de conservation des données', 'Data Retention Policy'],

  // Policy content/scope/audience
  ['Ensemble des collaborateurs de DEKRA Maroc, sous-traitants et partenaires', 'All DEKRA Maroc employees, subcontractors and partners'],
  ['Tous les collaborateurs de DEKRA Maroc', 'All DEKRA Maroc employees'],
  ['Ensemble des actifs informationnels de DEKRA Maroc', 'All DEKRA Maroc information assets'],
  ['Définir les règles de sécurité de l'information applicables à l'ensemble de l'organisation', 'Define information security rules applicable across the entire organization'],
  ['Encadrer l'accès aux systèmes d'information de DEKRA Maroc', 'Govern access to DEKRA Maroc information systems'],
  ['Garantir la disponibilité des données critiques en cas de sinistre', 'Ensure availability of critical data in the event of a disaster'],
  ['Standardiser la réponse aux incidents de sécurité', 'Standardize security incident response'],
  ['Assurer la continuité des activités critiques de DEKRA Maroc', 'Ensure continuity of DEKRA Maroc critical operations'],
  ['Encadrer l'utilisation des ressources informatiques', 'Govern the use of IT resources'],
  ['Gérer les risques liés aux fournisseurs et prestataires tiers', 'Manage risks related to third-party vendors and providers'],
  ['Classifier l'information selon sa sensibilité', 'Classify information according to its sensitivity'],
  ['Identifier et remédier aux vulnérabilités techniques', 'Identify and remediate technical vulnerabilities'],
  ['Sécuriser les accès distants aux ressources de l'organisation', 'Secure remote access to organizational resources'],
  ['Protéger la confidentialité des données via le chiffrement', 'Protect data confidentiality through encryption'],
  ['Protéger les installations physiques contre les intrusions', 'Protect physical premises against intrusions'],

  // Policy statuses
  ['Approuvée', 'Approved'],
  ['En révision', 'Under Review'],
  ['Brouillon', 'Draft'],

  // Asset names
  ['Serveur HP ProLiant DC-CAS-01', 'HP ProLiant Server DC-CAS-01'],
  ['Serveur HP ProLiant DC-CAS-02', 'HP ProLiant Server DC-CAS-02'],
  ['Base de données Oracle Inspection', 'Oracle Inspection Database'],
  ['Base de données Oracle RH', 'Oracle HR Database'],
  ['Portail Client Web DEKRA', 'DEKRA Web Client Portal'],
  ['Système de messagerie Microsoft Exchange', 'Microsoft Exchange Email System'],
  ['Solution de sauvegarde Veeam', 'Veeam Backup Solution'],
  ['Pare-feu Cisco ASA Casablanca', 'Cisco ASA Firewall Casablanca'],
  ['Switch Cisco Catalyst Centre Casablanca', 'Cisco Catalyst Switch Casablanca Center'],
  ['Postes de travail techniciens inspection', 'Inspection Technician Workstations'],
  ['Ordinateurs portables équipe DSI', 'IT Department Laptops'],
  ['Tablettes terrain inspecteurs', 'Field Inspector Tablets'],
  ['Système de vidéosurveillance CCTV', 'CCTV Surveillance System'],
  ['Contrôle d'accès badges RFID', 'RFID Badge Access Control System'],
  ['Active Directory Windows Server', 'Windows Server Active Directory'],
  ['Antivirus centralisé SentinelOne', 'SentinelOne Centralized Antivirus'],
  ['VPN Cisco AnyConnect', 'Cisco AnyConnect VPN'],
  ['Microsoft 365 (Exchange, Teams, SharePoint)', 'Microsoft 365 (Exchange, Teams, SharePoint)'],
  ['Logiciel SIVI Gestion Inspections', 'SIVI Inspection Management Software'],
  ['NAS Synology Sauvegarde Locale', 'Synology NAS Local Backup'],
  ['Générateurs électriques centres inspection', 'Inspection Center Power Generators'],
  ['Application mobile DEKRA Inspecteurs', 'DEKRA Inspector Mobile App'],

  // Asset descriptions
  ['Serveur principal hébergeant le système SIVI de gestion des inspections techniques', 'Primary server hosting the SIVI technical inspection management system'],
  ['Serveur secondaire de redondance pour les applications métier critiques', 'Secondary redundancy server for critical business applications'],
  ['Base de données principale contenant les dossiers d'inspection de tous les véhicules au Maroc', 'Main database containing inspection records for all vehicles in Morocco'],
  ['Base de données RH avec données personnelles des 500+ employés', 'HR database containing personal data of 500+ employees'],
  ['Portail web permettant la prise de rendez-vous et la consultation des résultats d'inspection', 'Web portal for appointment booking and inspection result consultation'],
  ['Serveur de messagerie hébergeant toutes les communications internes et externes', 'Email server hosting all internal and external communications'],
  ['Solution de sauvegarde automatisée pour les serveurs critiques - RPO 4h', 'Automated backup solution for critical servers - RPO 4h'],
  ['Pare-feu principal protégeant le périmètre réseau du siège social', 'Primary firewall protecting the headquarters network perimeter'],
  ['Infrastructure réseau du centre d'inspection de Casablanca', 'Network infrastructure of the Casablanca inspection center'],
  ['800 postes Windows 10/11 déployés dans les centres d'inspection à travers le Maroc', '800 Windows 10/11 workstations deployed across inspection centers throughout Morocco'],
  ['120 laptops utilisés par l'équipe IT et les managers', '120 laptops used by the IT team and managers'],
  ['250 tablettes utilisées par les inspecteurs sur le terrain pour saisir les résultats', '250 tablets used by field inspectors to record inspection results'],
  ['Système de vidéosurveillance couvrant l'ensemble des sites DEKRA Maroc', 'Video surveillance system covering all DEKRA Maroc sites'],
  ['Système de contrôle d'accès physique par badges dans les locaux sensibles', 'Physical access control system using badges in sensitive premises'],
  ['Annuaire d'entreprise gérant les 500+ comptes utilisateurs', 'Corporate directory managing 500+ user accounts'],
  ['Solution EDR déployée sur l'ensemble du parc informatique', 'EDR solution deployed across the entire IT fleet'],
  ['Solution d'accès distant sécurisé pour le personnel en télétravail', 'Secure remote access solution for remote workers'],
  ['Suite collaborative cloud utilisée pour la messagerie, réunions et stockage documentaire', 'Cloud collaboration suite used for email, meetings and document storage'],
  ['Logiciel métier cœur de DEKRA Maroc - gestion des inspections techniques véhicules', 'Core business software for DEKRA Maroc - vehicle technical inspection management'],
  ['Système de sauvegarde local redondant dans chaque centre d'inspection', 'Redundant local backup system at each inspection center'],
  ['Groupes électrogènes assurant la continuité électrique lors des coupures', 'Power generators ensuring electrical continuity during outages'],
  ['Application mobile Android/iOS pour les inspecteurs terrain', 'Android/iOS mobile app for field inspectors'],

  // Salle serveurs
  ['Datacenter Casablanca', 'Casablanca Datacenter'],
  ['Salle technique Rabat', 'Rabat Technical Room'],
  ['Ensemble des sites DEKRA Maroc', 'All DEKRA Maroc sites'],
  ['Siège social - Casablanca', 'Headquarters - Casablanca'],
  ['Centre inspection Casablanca', 'Casablanca Inspection Center'],

  // Incident titles/descriptions
  ['Tentative de phishing ciblant la comptabilité', 'Phishing Attempt Targeting the Accounting Team'],
  ['Accès non autorisé au portail RH', 'Unauthorized Access to the HR Portal'],
  ['Infection malware sur poste de travail Fès', 'Malware Infection on Fes Workstation'],
  ['Panne serveur SIVI - interruption service 4h', 'SIVI Server Outage - 4h Service Interruption'],
  ['Perte d'un ordinateur portable en déplacement', 'Lost Laptop During Business Travel'],
  ['Tentative d'intrusion physique centre Rabat', 'Physical Intrusion Attempt at Rabat Center'],
  ['Fuite accidentelle de données clients via email', 'Accidental Customer Data Leak via Email'],
  ['Défacement du site web DEKRA Maroc', 'DEKRA Maroc Website Defacement'],
  ['Attaque DDoS sur le portail client', 'DDoS Attack on Client Portal'],

  // Incident descriptions
  ['Email frauduleux imitant un partenaire bancaire envoyé à 12 employés du département comptabilité, 2 ont cliqué sur le lien', 'Fraudulent email impersonating a banking partner sent to 12 accounting employees, 2 clicked the link'],
  ['Un ancien stagiaire a tenté d'accéder au portail RH avec ses anciennes credentials après la fin de son contrat', 'A former intern attempted to access the HR portal using old credentials after contract end'],
  ['Détection d'un cheval de Troie sur le poste du responsable du centre d'inspection de Fès suite à téléchargement d'un logiciel non autorisé', 'Trojan detected on the Fes inspection center manager workstation following unauthorized software download'],
  ['Défaillance matérielle du serveur principal SIVI causant 4h d'interruption des opérations d'inspection dans la région Casablanca-Settat', 'Hardware failure on the primary SIVI server causing 4h interruption of inspection operations in the Casablanca-Settat region'],
  ['Un manager a perdu son ordinateur portable lors d'un déplacement à Marrakech. Le disque dur était chiffré avec BitLocker', 'A manager lost their laptop during a trip to Marrakech. The hard drive was encrypted with BitLocker'],
  ['Tentative d'intrusion physique nocturne au centre de Rabat. Détectée par le système d'alarme, aucune intrusion effective', 'Nocturnal physical intrusion attempt at the Rabat center. Detected by the alarm system, no actual intrusion'],
  ['Un employé a envoyé par erreur un fichier Excel contenant les données de 150 clients à un destinataire externe', 'An employee accidentally sent an Excel file containing 150 client records to an external recipient'],
  ['Le site web public de DEKRA Maroc a été défacé par un groupe de hackers militants. Restauration en 2h', 'The DEKRA Maroc public website was defaced by a hacktivist group. Restored within 2 hours'],
  ['Attaque par déni de service distribué sur le portail client causant 3h d'indisponibilité', 'Distributed denial-of-service attack on the client portal causing 3h of downtime'],

  // Incident fields
  ['Isolation du poste et scan antivirus complet', 'Workstation isolation and full antivirus scan'],
  ['Blocage du compte, notification à la DRH', 'Account blocked, HR notified'],
  ['Activation du PRA, basculement sur serveur secondaire', 'DR plan activated, failover to secondary server'],
  ['Révocation immédiate des accès, signalement à la CNDP', 'Immediate access revocation, reported to CNDP'],
  ['Restauration depuis sauvegarde, renforcement pare-feu', 'Restored from backup, firewall hardened'],
  ['Activation protection DDoS Cloudflare', 'Cloudflare DDoS protection activated'],
  ['Formation de sensibilisation au phishing', 'Phishing awareness training'],
  ['Logiciel non autorisé installé par l'utilisateur', 'Unauthorized software installed by the user'],
  ['Absence de redondance matérielle', 'Lack of hardware redundancy'],
  ['Contrôle de sécurité physique à renforcer', 'Physical security controls need strengthening'],
  ['Erreur humaine - absence de procédure d'envoi sécurisé', 'Human error - no secure sending procedure in place'],
  ['Vulnérabilité dans le CMS du site web', 'Vulnerability in the website CMS'],
  ['Absence de protection DDoS', 'Lack of DDoS protection'],
  ['Lien de phishing redirigé vers faux site bancaire', 'Phishing link redirected to fake banking site'],
  ['Impact limité grâce au chiffrement BitLocker', 'Impact limited thanks to BitLocker encryption'],
  ['Aucune intrusion réelle', 'No actual intrusion occurred'],
  ['Données de 150 clients exposées temporairement', '150 client records temporarily exposed'],
  ['Site web indisponible 2h', 'Website unavailable for 2 hours'],
  ['Portail indisponible 3h, perte de CA estimée 50k MAD', 'Portal unavailable 3h, estimated revenue loss 50k MAD'],
  ['Mise à jour urgente du CMS et durcissement', 'Emergency CMS update and hardening'],
  ['Activation protection anti-DDoS et réponse complète', 'Anti-DDoS protection activated and full response completed'],

  // Reporter/assignee
  ['Département Comptabilité', 'Accounting Department'],
  ['Système de monitoring', 'Monitoring System'],
  ['Équipe IT', 'IT Team'],
  ['Équipe Sécurité', 'Security Team'],
  ['Responsable du centre Fès', 'Fes Center Manager'],
  ['Responsable centre Rabat', 'Rabat Center Manager'],
  ['Réception Casablanca', 'Casablanca Reception'],

  // Audit titles
  ['Audit Interne SMSI - Périmètre Complet', 'Internal ISMS Audit - Full Scope'],
  ['Audit Interne - Contrôles Techniques', 'Internal Audit - Technical Controls'],
  ['Audit de Certification ISO 27001:2022', 'ISO 27001:2022 Certification Audit'],
  ['Audit de Surveillance ISO 27001', 'ISO 27001 Surveillance Audit'],
  ['Test d'Intrusion (Pentest) Externe', 'External Penetration Test'],
  ['Audit Fournisseurs Critiques', 'Critical Vendor Audit'],

  // Audit descriptions
  ['Audit complet du SMSI couvrant l'ensemble des clauses ISO 27001:2022 et des contrôles Annex A', 'Full ISMS audit covering all ISO 27001:2022 clauses and Annex A controls'],
  ['Audit ciblé sur les contrôles techniques : accès logiques, chiffrement, surveillance, gestion des vulnérabilités', 'Targeted audit on technical controls: logical access, encryption, monitoring, vulnerability management'],
  ['Audit de certification par organisme accrédité - première certification ISO 27001:2022 de DEKRA Maroc', 'Certification audit by accredited body - first ISO 27001:2022 certification for DEKRA Maroc'],
  ['Audit de surveillance annuel pour maintien de la certification ISO 27001', 'Annual surveillance audit to maintain ISO 27001 certification'],
  ['Test d'intrusion externe sur le périmètre exposé : portail web, VPN, messagerie', 'External penetration test on exposed perimeter: web portal, VPN, email'],
  ['Audit de conformité sécurité des principaux fournisseurs de services IT', 'Security compliance audit of key IT service providers'],

  // Audit findings
  ['3 non-conformités mineures identifiées : documentation des procédures incomplète, revue des accès en retard, journaux d'audit non centralisés', '3 minor nonconformities identified: incomplete procedure documentation, overdue access review, audit logs not centralized'],
  ['Chiffrement non systématique sur les postes de travail anciens, absence de MFA sur certains accès critiques', 'Inconsistent encryption on legacy workstations, MFA missing on some critical access points'],
  ['Audit planifié avec Bureau Veritas pour Q4 2026', 'Audit scheduled with Bureau Veritas for Q4 2026'],
  ['Audit prévu après certification initiale', 'Audit planned after initial certification'],
  ['Vulnérabilités critiques identifiées dans l'application web et le service VPN', 'Critical vulnerabilities identified in the web application and VPN service'],
  ['2 fournisseurs sur 4 présentent des lacunes dans leur politique de sécurité', '2 out of 4 vendors show gaps in their security policy'],

  // Compliance clauses
  ['Comprendre les enjeux internes et externes impactant la sécurité de l'information', 'Understand internal and external issues impacting information security'],
  ['Identifier les parties intéressées et leurs exigences en matière de sécurité', 'Identify interested parties and their security requirements'],
  ['Définir le périmètre du SMSI de DEKRA Maroc', 'Define the scope of the DEKRA Maroc ISMS'],
  ['Établir, mettre en œuvre, maintenir et améliorer le SMSI', 'Establish, implement, maintain and improve the ISMS'],
  ['La direction générale doit démontrer son engagement envers le SMSI', 'Top management must demonstrate commitment to the ISMS'],
  ['Définir et communiquer la politique de sécurité de l'information', 'Define and communicate the information security policy'],
  ['Attribuer les responsabilités et autorités liées à la sécurité de l'information', 'Assign roles and responsibilities related to information security'],
  ['Identifier et traiter les risques et opportunités', 'Identify and address risks and opportunities'],
  ['Réaliser une appréciation des risques de sécurité de l'information', 'Conduct an information security risk assessment'],
  ['Définir et mettre en œuvre un plan de traitement des risques', 'Define and implement a risk treatment plan'],
  ['Définir des objectifs de sécurité mesurables et un plan pour les atteindre', 'Define measurable security objectives and a plan to achieve them'],
  ['S'assurer de la disponibilité des ressources nécessaires au SMSI', 'Ensure availability of resources needed for the ISMS'],
  ['Développer les compétences requises pour la sécurité de l'information', 'Develop competencies required for information security'],
  ['S'assurer que le personnel est sensibilisé à la politique et aux objectifs SMSI', 'Ensure staff are aware of the ISMS policy and objectives'],
  ['Définir les communications internes et externes liées au SMSI', 'Define internal and external communications related to the ISMS'],
  ['Maintenir et contrôler les informations documentées requises', 'Maintain and control required documented information'],
  ['Planifier, mettre en œuvre et contrôler les processus opérationnels', 'Plan, implement and control operational processes'],
  ['Réaliser régulièrement des appréciations des risques', 'Regularly conduct risk assessments'],
  ['Mettre en œuvre le plan de traitement des risques', 'Implement the risk treatment plan'],
  ['Surveiller, mesurer, analyser et évaluer la performance du SMSI', 'Monitor, measure, analyze and evaluate ISMS performance'],
  ['Mener des audits internes à intervalles planifiés', 'Conduct internal audits at planned intervals'],
  ['La direction doit procéder à une revue du SMSI à intervalles planifiés', 'Management must review the ISMS at planned intervals'],
  ['Traiter les non-conformités et mettre en œuvre des actions correctives', 'Address nonconformities and implement corrective actions'],
  ['Améliorer en continu la pertinence, l'adéquation et l'efficacité du SMSI', 'Continually improve the suitability, adequacy and effectiveness of the ISMS'],

  // Compliance evidence
  ['Analyse du contexte documentée, SWOT sécurité disponible', 'Documented context analysis, security SWOT available'],
  ['Registre des parties intéressées à jour', 'Updated interested parties register'],
  ['Document de périmètre SMSI v2.1 approuvé', 'ISMS scope document v2.1 approved'],
  ['SMSI établi et opérationnel depuis Jan 2025', 'ISMS established and operational since Jan 2025'],
  ['Lettre d'engagement DG signée, présence aux revues de direction', 'Signed DG commitment letter, attendance at management reviews'],
  ['Politique SMSI v3.0 approuvée et communiquée', 'ISMS Policy v3.0 approved and communicated'],
  ['Matrice des responsabilités RACI validée', 'RACI responsibility matrix validated'],
  ['Registre des risques à jour, méthodologie documentée', 'Risk register up to date, methodology documented'],
  ['18 risques évalués, rapport d'appréciation disponible', '18 risks assessed, assessment report available'],
  ['Plan de traitement des risques approuvé par la direction', 'Risk treatment plan approved by management'],
  ['8 objectifs SMSI définis avec KPIs et responsables', '8 ISMS objectives defined with KPIs and owners'],
  ['Budget SMSI alloué, ressources humaines identifiées', 'ISMS budget allocated, human resources identified'],
  ['Plan de formation SMSI exécuté à 85%', 'ISMS training plan 85% executed'],
  ['Sessions de sensibilisation trimestrielles réalisées', 'Quarterly awareness sessions conducted'],
  ['Plan de communication SMSI validé', 'ISMS communication plan approved'],
  ['Liste des documents SMSI maintenue dans SharePoint', 'ISMS document list maintained in SharePoint'],
  ['Procédures opérationnelles documentées et appliquées', 'Operational procedures documented and applied'],
  ['Appréciation des risques réalisée Q1 2026', 'Risk assessment conducted Q1 2026'],
  ['Contrôles Annex A en cours de déploiement - 67% implémentés', 'Annex A controls being deployed - 67% implemented'],
  ['Tableau de bord KPI sécurité mis à jour mensuellement', 'Security KPI dashboard updated monthly'],
  ['2 audits internes réalisés en 2025', '2 internal audits conducted in 2025'],
  ['Revue de direction Q1 2026 réalisée', 'Q1 2026 management review completed'],
  ['5 actions correctives ouvertes suite aux audits', '5 corrective actions open following audits'],
  ['Plan d'amélioration continue actif', 'Active continual improvement plan'],

  // Objectives
  ['Obtenir la certification ISO 27001:2022', 'Achieve ISO 27001:2022 Certification'],
  ['Réduire le taux de susceptibilité au phishing', 'Reduce Phishing Susceptibility Rate'],
  ['Chiffrement complet des données sensibles', 'Full Encryption of Sensitive Data'],
  ['Zéro vulnérabilité critique non traitée en 30 jours', 'Zero Critical Vulnerabilities Unpatched Beyond 30 Days'],
  ['Taux de complétion formation sécurité à 95%', 'Security Training Completion Rate to 95%'],
  ['Réduire le délai moyen de réponse aux incidents', 'Reduce Mean Time to Respond to Incidents'],
  ['Mettre en place un programme de gestion des fournisseurs', 'Implement Vendor Risk Management Program'],
  ['Atteindre un score de conformité ISO 27001 de 90%', 'Achieve ISO 27001 Compliance Score of 90%'],

  ['Passer avec succès l'audit de certification ISO 27001:2022 avec Bureau Veritas avant fin Q4 2026', 'Successfully pass the ISO 27001:2022 certification audit with Bureau Veritas before end of Q4 2026'],
  ['Réduire le nombre d'employés cliquant sur des liens de phishing simulés à moins de 5%', 'Reduce the number of employees clicking on simulated phishing links to below 5%'],
  ['Chiffrer 100% des données sensibles au repos et en transit sur l'ensemble de l'infrastructure', 'Encrypt 100% of sensitive data at rest and in transit across the entire infrastructure'],
  ['Aucune vulnérabilité critique ne doit rester non traitée plus de 30 jours après sa découverte', 'No critical vulnerability should remain unaddressed more than 30 days after discovery'],
  ['Atteindre 95% de completion des formations sécurité obligatoires pour tous les employés', 'Achieve 95% completion of mandatory security training for all employees'],
  ['Réduire le MTTD sous 1h et le MTTR sous 4h pour les incidents de sécurité', 'Reduce MTTD below 1h and MTTR below 4h for security incidents'],
  ['Évaluer et documenter le niveau de risque de tous les fournisseurs critiques', 'Assess and document the risk level of all critical vendors'],
  ['Atteindre un taux de conformité global de 90% sur les clauses ISO 27001:2022', 'Achieve an overall compliance rate of 90% on ISO 27001:2022 clauses'],

  ['Réussir l'audit de certification', 'Pass certification audit'],
  ['Moins de 5% aux tests de phishing simulé', 'Less than 5% in simulated phishing tests'],
  ['100% des données sensibles chiffrées', '100% of sensitive data encrypted'],
  ['Délai de remédiation max 30 jours', 'Maximum 30-day remediation period'],
  ['95% de completion', '95% completion rate'],
  ['MTTD < 1h, MTTR < 4h', 'MTTD < 1h, MTTR < 4h'],
  ['100% des fournisseurs critiques évalués', '100% of critical vendors assessed'],
  ['Score de conformité 90%', '90% compliance score'],

  ['Tests de phishing simulés mensuels', 'Monthly simulated phishing tests'],
  ['Inventaire de chiffrement mensuel', 'Monthly encryption inventory'],
  ['Scan de vulnérabilités hebdomadaire', 'Weekly vulnerability scan'],
  ['Rapport de completion mensuel', 'Monthly completion report'],
  ['Métriques SIEM hebdomadaires', 'Weekly SIEM metrics'],
  ['Revue fournisseurs trimestrielle', 'Quarterly vendor review'],
  ['Tableau de bord conformité mensuel', 'Monthly compliance dashboard'],
  ['Résultats du pré-audit SMSI', 'ISMS pre-audit results'],

  // Scope
  ['DEKRA Maroc est une société d'inspection et de certification internationale implantée au Maroc depuis 2007. Leader dans l'inspection technique des véhicules, l'expertise automobile, l'inspection industrielle et la gestion des sinistres, DEKRA Maroc opère dans les 12 régions du Royaume à travers un réseau de centres d'inspection agréés.', 'DEKRA Maroc is an international inspection and certification company established in Morocco since 2007. A leader in vehicle technical inspection, automotive expertise, industrial inspection and claims management, DEKRA Maroc operates across all 12 regions of the Kingdom through a network of accredited inspection centers.'],
  ['Dépendance aux prestataires IT externes, compétences cybersécurité à renforcer en interne, budget SMSI limité, résistance au changement de certaines équipes opérationnelles', 'Dependency on external IT providers, internal cybersecurity skills needing reinforcement, limited ISMS budget, operational team resistance to change'],
  ['Augmentation des cyberattaques ciblant le secteur des services au Maroc, évolution réglementaire rapide (Loi 05-20), concurrence accrue, risques géopolitiques régionaux', 'Increasing cyberattacks targeting the services sector in Morocco, rapid regulatory changes (Law 05-20), increased competition, regional geopolitical risks'],
  ['Ministère du Transport (autorité de tutelle), CNDP (protection des données), IRCAM, clients B2B et particuliers, fournisseurs IT, auditeurs Bureau Veritas, employés et sous-traitants', 'Ministry of Transport (supervisory authority), CNDP (data protection), IRCAM, B2B and individual clients, IT vendors, Bureau Veritas auditors, employees and subcontractors'],
  ['Conformité Loi 09-08 sur la protection des données, Loi 05-20 sur la cybersécurité, ISO/IEC 17020:2012, exigences de confidentialité des clients entreprises, SLA contractuels avec les partenaires', 'Compliance with Law 09-08 on data protection, Law 05-20 on cybersecurity, ISO/IEC 17020:2012, enterprise client confidentiality requirements, contractual SLAs with partners'],
  ['Le SMSI de DEKRA Maroc couvre l'ensemble des systèmes d'information, des processus métier et des actifs informationnels utilisés dans le cadre des activités d'inspection technique des véhicules, d'expertise automobile, d'inspection industrielle et de gestion des sinistres, incluant le siège social de Casablanca et les centres d'inspection régionaux.', 'The DEKRA Maroc ISMS covers all information systems, business processes and information assets used in vehicle technical inspection, automotive expertise, industrial inspection and claims management activities, including the Casablanca headquarters and regional inspection centers.'],
  ['Siège social Casablanca, centres régionaux : Rabat, Marrakech, Fès, Tanger, Agadir, Oujda, Meknès, El Jadida, Kénitra, Béni Mellal', 'Headquarters Casablanca, regional centers: Rabat, Marrakech, Fes, Tangier, Agadir, Oujda, Meknes, El Jadida, Kenitra, Beni Mellal'],
  ['Inspection technique des véhicules, expertise automobile, inspection industrielle, gestion des sinistres, services administratifs et supports (IT, RH, Finance, Juridique)', 'Vehicle technical inspection, automotive expertise, industrial inspection, claims management, administrative and support services (IT, HR, Finance, Legal)'],
  ['SIVI (gestion inspections), Active Directory, Microsoft 365, Oracle Database, portail client web, VPN, antivirus, CCTV, badges RFID', 'SIVI (inspection management), Active Directory, Microsoft 365, Oracle Database, client web portal, VPN, antivirus, CCTV, RFID badges'],
  ['Loi 09-08 (protection données personnelles), Loi 05-20 (cybersécurité), Dahir 1-07-129, ISO/IEC 17020:2012, ISO 9001:2015, ISO 45001:2018', 'Law 09-08 (personal data protection), Law 05-20 (cybersecurity), Dahir 1-07-129, ISO/IEC 17020:2012, ISO 9001:2015, ISO 45001:2018'],
  ['Systèmes informatiques des partenaires commerciaux externes non gérés par DEKRA Maroc, équipements personnels des employés non fournis par l'entreprise', 'IT systems of external commercial partners not managed by DEKRA Maroc, personal devices of employees not provided by the company'],

  // Vendors
  ['Suite collaborative cloud Microsoft 365, licences Azure AD', 'Microsoft 365 cloud collaboration suite, Azure AD licenses'],
  ['Hébergement serveurs et infrastructure cloud (Private Cloud Maroc)', 'Server hosting and cloud infrastructure (Private Cloud Morocco)'],
  ['Opérateur télécom principal - liaisons MPLS inter-sites, accès Internet', 'Primary telecom operator - inter-site MPLS links, Internet access'],
  ['Équipements réseau (pare-feu, switches, routeurs, VPN)', 'Network equipment (firewalls, switches, routers, VPN)'],
  ['Licences bases de données Oracle, support maintenance', 'Oracle database licenses, maintenance support'],
  ['Logiciel SIRH (Système Information Ressources Humaines)', 'HRIS software (Human Resources Information System)'],
  ['Logiciel métier SIVI de gestion des inspections techniques', 'SIVI business software for technical inspection management'],
  ['Onduleurs, groupes électrogènes, infrastructure électrique', 'UPS systems, generators, electrical infrastructure'],
  ['Gardiennage et sécurité physique des centres d'inspection', 'Guarding and physical security for inspection centers'],
  ['Audit de certification ISO 27001, prestation de conseil qualité', 'ISO 27001 certification audit, quality consulting'],
  ['Infrastructure IT cloud hybride et services de cybersécurité', 'Hybrid cloud IT infrastructure and cybersecurity services'],
  ['Audit SMSI, conseil en gestion des risques et conformité', 'ISMS audit, risk management and compliance consulting'],

  // Vendor contacts
  ['Compte Enterprise - Siège Microsoft France', 'Enterprise account - Microsoft France HQ'],
  ['Support technique OVHcloud Maroc', 'OVHcloud Morocco technical support'],
  ['Responsable Grand Compte Maroc Telecom', 'Maroc Telecom Key Account Manager'],
  ['Ingénieur Réseau Cisco Partenaire', 'Cisco Partner Network Engineer'],
  ['Support Oracle Gold Partner Maroc', 'Oracle Gold Partner Morocco Support'],
  ['Chef de Projet SopraHR Maroc', 'SopraHR Morocco Project Manager'],
  ['Support Technique SIVI', 'SIVI Technical Support'],
  ['Responsable Compte Schneider Maroc', 'Schneider Morocco Account Manager'],
  ['Directeur Opérations G4S Maroc', 'G4S Morocco Operations Director'],
  ['Responsable Certification Bureau Veritas Maroc', 'Bureau Veritas Morocco Certification Manager'],
  ['Responsable Commercial IBM Maroc', 'IBM Morocco Commercial Manager'],
  ['Directeur Advisory PwC Maroc', 'PwC Morocco Advisory Director'],

  // Vendor contracts
  ['Contrat Microsoft EA - Renouvellement annuel', 'Microsoft EA Contract - Annual renewal'],
  ['Contrat hébergement 3 ans avec SLA garanti', '3-year hosting contract with guaranteed SLA'],
  ['Contrat cadre MPLS - Durée 3 ans', 'MPLS framework contract - 3-year term'],
  ['Contrat maintenance matériel 2 ans', '2-year equipment maintenance contract'],
  ['Licence perpétuelle Oracle + Support annuel', 'Oracle perpetual license + Annual support'],
  ['Contrat SaaS annuel SopraHR', 'SopraHR annual SaaS contract'],
  ['Licence SIVI + Maintenance 5 ans', 'SIVI license + 5-year maintenance'],
  ['Contrat maintenance infrastructure électrique', 'Electrical infrastructure maintenance contract'],
  ['Contrat gardiennage 2 ans - Renouvellement prévu', '2-year guarding contract - Renewal planned'],
  ['Contrat de certification ISO 27001 - Bureau Veritas', 'ISO 27001 certification contract - Bureau Veritas'],
  ['Contrat services managés IBM - 3 ans', 'IBM managed services contract - 3 years'],
  ['Contrat conseil annuel PwC', 'Annual PwC consulting contract'],

  // Changes
  ['Migration vers Microsoft 365', 'Migration to Microsoft 365'],
  ['Déploiement nouveau pare-feu nouvelle génération', 'Next-Generation Firewall Deployment'],
  ['Mise à niveau infrastructure VPN', 'VPN Infrastructure Upgrade'],
  ['Remplacement système de sauvegarde', 'Backup System Replacement'],
  ['Déploiement solution EDR SentinelOne', 'SentinelOne EDR Solution Deployment'],
  ['Activation MFA sur Microsoft 365', 'MFA Activation on Microsoft 365'],
  ['Mise à jour critique Oracle Database', 'Oracle Database Critical Update'],
  ['Déploiement SIEM Splunk', 'Splunk SIEM Deployment'],
  ['Segmentation réseau DMZ', 'DMZ Network Segmentation'],
  ['Chiffrement disques durs postes de travail', 'Workstation Hard Drive Encryption'],

  ['Migration des 500 boîtes mail vers la plateforme cloud Microsoft 365 avec Teams et SharePoint', 'Migration of 500 mailboxes to the Microsoft 365 cloud platform with Teams and SharePoint'],
  ['Remplacement des pare-feu Cisco ASA par des pare-feu Palo Alto Networks PA-3220 next-gen', 'Replacement of Cisco ASA firewalls with Palo Alto Networks PA-3220 next-gen firewalls'],
  ['Remplacement du VPN SSL par une solution ZTNA (Zscaler Private Access) pour l'accès distant sécurisé', 'Replacement of SSL VPN with a ZTNA solution (Zscaler Private Access) for secure remote access'],
  ['Remplacement du système de sauvegarde Symantec obsolète par Veeam Backup & Replication v12', 'Replacement of the obsolete Symantec backup system with Veeam Backup & Replication v12'],
  ['Déploiement de la solution EDR SentinelOne sur l'ensemble du parc (800 postes, 120 serveurs)', 'Deployment of SentinelOne EDR solution across the entire fleet (800 workstations, 120 servers)'],
  ['Activation de l'authentification multifacteurs pour tous les comptes Microsoft 365', 'Activation of multi-factor authentication for all Microsoft 365 accounts'],
  ['Application du patch critique Oracle CPU Q1 2026 sur les serveurs de production', 'Application of critical Oracle CPU Q1 2026 patch on production servers'],
  ['Mise en place d'un SIEM Splunk Enterprise pour la centralisation des logs et détection des menaces', 'Implementation of Splunk Enterprise SIEM for log centralization and threat detection'],
  ['Création d'une DMZ pour isoler les serveurs exposés sur Internet (portail web, serveur mail)', 'Creation of a DMZ to isolate Internet-facing servers (web portal, mail server)'],
  ['Activation de BitLocker sur l'ensemble des postes de travail et laptops', 'Activation of BitLocker on all workstations and laptops'],

  ['Impact fort - concerne l'ensemble des utilisateurs', 'High impact - affects all users'],
  ['Impact moyen - sécurité périmétrique améliorée', 'Medium impact - improved perimeter security'],
  ['Impact moyen - accès distant sécurisé', 'Medium impact - secured remote access'],
  ['Impact faible - transparent pour les utilisateurs', 'Low impact - transparent to users'],
  ['Impact fort - sécurité endpoints', 'High impact - endpoint security'],
  ['Impact faible - expérience utilisateur légèrement modifiée', 'Low impact - slightly modified user experience'],
  ['Impact faible - maintenance planifiée', 'Low impact - planned maintenance'],
  ['Impact fort - nouvelle capacité de détection', 'High impact - new detection capability'],
  ['Impact technique fort - reconfiguration réseau', 'High technical impact - network reconfiguration'],
  ['Impact faible - transparent pour les utilisateurs', 'Low impact - transparent to users'],

  // CAPA
  ['Lacune formation anti-phishing - taux d'échec élevé', 'Anti-Phishing Training Gap - High Failure Rate'],
  ['Faiblesse contrôle d'accès - comptes orphelins', 'Access Control Weakness - Orphan Accounts'],
  ['Procédure de sauvegarde obsolète', 'Outdated Backup Procedure'],
  ['Absence de procédure de gestion des médias amovibles', 'Lack of Removable Media Management Procedure'],
  ['Journaux d'audit non centralisés', 'Audit Logs Not Centralized'],
  ['Absence de test de restauration régulier', 'Lack of Regular Restoration Testing'],
  ['Gestion des correctifs non formalisée', 'Formalized Patch Management Missing'],
  ['Formation SMSI insuffisante pour les managers', 'Insufficient ISMS Training for Managers'],
  ['Absence de procédure de clean desk', 'Clear-Desk Procedure Missing'],
  ['Revue des droits d'accès en retard', 'Overdue Access Rights Review'],

  ['Audit interne Q1 2025 a révélé 23% des employés ont cliqué sur un lien de phishing simulé, dépassant le seuil de 10%', 'Q1 2025 internal audit revealed 23% of employees clicked on a simulated phishing link, exceeding the 10% threshold'],
  ['Revue des comptes Active Directory a identifié 47 comptes orphelins non désactivés après départ des employés', 'Active Directory account review identified 47 orphan accounts not deactivated after employee departure'],
  ['La procédure de sauvegarde date de 2022 et ne couvre pas les nouveaux systèmes Oracle et Microsoft 365', 'The backup procedure dates from 2022 and does not cover the new Oracle and Microsoft 365 systems'],
  ['Audit physique a révélé l'absence de procédure documentée pour la gestion des clés USB et disques durs externes', 'Physical audit revealed the absence of a documented procedure for USB drives and external hard disk management'],
  ['Les journaux des 12 serveurs de production ne sont pas centralisés, rendant la détection des incidents difficile', 'Logs from the 12 production servers are not centralized, making incident detection difficult'],
  ['Aucun test de restauration des sauvegardes n'a été réalisé depuis 18 mois', 'No backup restoration test has been conducted in the past 18 months'],
  ['La gestion des correctifs de sécurité n'est pas formalisée, causant des délais de déploiement variables', 'Security patch management is not formalized, causing variable deployment delays'],
  ['Seulement 45% des managers ont suivi la formation SMSI obligatoire', 'Only 45% of managers completed the mandatory ISMS training'],
  ['Plusieurs postes de travail photographiés avec des post-its contenant des mots de passe', 'Several workstations photographed with sticky notes containing passwords'],
  ['La revue semestrielle des droits d'accès est en retard de 4 mois', 'The semi-annual access rights review is 4 months overdue'],

  ['Refonte du programme de formation phishing avec simulations mensuelles', 'Overhaul of phishing training program with monthly simulations'],
  ['Audit et nettoyage de tous les comptes Active Directory', 'Audit and cleanup of all Active Directory accounts'],
  ['Mise à jour et validation de la procédure de sauvegarde', 'Update and validate the backup procedure'],
  ['Rédaction et déploiement d'une procédure de gestion des médias amovibles', 'Draft and deploy a removable media management procedure'],
  ['Déploiement SIEM Splunk pour centralisation des logs', 'Deploy Splunk SIEM for log centralization'],
  ['Planification et exécution de tests de restauration trimestriels', 'Plan and execute quarterly restoration tests'],
  ['Déploiement outil WSUS et formalisation du processus de patch', 'Deploy WSUS tool and formalize the patching process'],
  ['Déploiement de la formation SMSI Manager obligatoire', 'Deploy mandatory ISMS Manager training'],
  ['Déploiement politique clear-desk et session de sensibilisation', 'Deploy clear-desk policy and awareness session'],
  ['Réalisation immédiate de la revue des droits d'accès', 'Immediately conduct access rights review'],

  ['Insuffisance formation utilisateurs', 'Insufficient user training'],
  ['Processus offboarding incomplet', 'Incomplete offboarding process'],
  ['Procédure non mise à jour depuis 3 ans', 'Procedure not updated for 3 years'],
  ['Absence de politique formelle', 'Lack of formal policy'],
  ['Architecture SIEM absente', 'Missing SIEM architecture'],
  ['Absence de procédure de test', 'Lack of testing procedure'],
  ['Outil de gestion des patches absent', 'Patch management tool missing'],
  ['Sensibilisation SMSI insuffisante', 'Insufficient ISMS awareness'],
  ['Absence de politique et sensibilisation', 'Lack of policy and awareness'],
  ['Charge de travail excessive de l\'équipe SMSI', 'Excessive ISMS team workload'],

  // Threats
  ['Menaces Persistantes Avancées (APT)', 'Advanced Persistent Threats (APT)'],
  ['Attaques Ransomware', 'Ransomware Attacks'],
  ['Phishing et Spear-Phishing', 'Phishing and Spear-Phishing'],
  ['Menaces Internes', 'Insider Threats'],
  ['Vol et Perte d'Équipements', 'Equipment Theft and Loss'],
  ['Attaques par Déni de Service (DDoS)', 'Denial of Service Attacks (DDoS)'],
  ['Exploitation de Vulnérabilités Zero-Day', 'Zero-Day Vulnerability Exploitation'],
  ['Attaques sur la Chaîne d'Approvisionnement', 'Supply Chain Attacks'],
  ['Catastrophes Naturelles et Pannes Électriques', 'Natural Disasters and Power Outages'],
  ['Erreurs Humaines et Mauvaises Configurations', 'Human Errors and Misconfigurations'],

  ['Groupes de cybercriminels sophistiqués ou étatiques ciblant les infrastructures critiques du secteur de l'inspection et certification au Maroc', 'Sophisticated criminal or state-sponsored groups targeting critical infrastructure in Morocco\'s inspection and certification sector'],
  ['Logiciels malveillants chiffrant les données contre rançon - menace n°1 pour les PME et ETI au Maroc selon DGSSI 2025', 'Malware encrypting data for ransom - the #1 threat for SMEs in Morocco according to DGSSI 2025'],
  ['Emails frauduleux ciblant les employés DEKRA Maroc pour voler des identifiants ou installer des malwares', 'Fraudulent emails targeting DEKRA Maroc employees to steal credentials or install malware'],
  ['Employés mécontents, sous-traitants malveillants ou inadvertances pouvant causer des incidents de sécurité', 'Disgruntled employees, malicious subcontractors or inadvertent actions causing security incidents'],
  ['Perte ou vol d'appareils portables contenant des données confidentielles DEKRA Maroc', 'Loss or theft of portable devices containing confidential DEKRA Maroc data'],
  ['Attaques saturant les ressources réseau rendant les services DEKRA Maroc indisponibles', 'Attacks saturating network resources making DEKRA Maroc services unavailable'],
  ['Exploitation de failles de sécurité non encore publiées dans les logiciels utilisés par DEKRA Maroc', 'Exploitation of unpublished security vulnerabilities in software used by DEKRA Maroc'],
  ['Compromission de fournisseurs de logiciels ou services utilisés par DEKRA Maroc (SIVI, Oracle, Microsoft)', 'Compromise of software or service providers used by DEKRA Maroc (SIVI, Oracle, Microsoft)'],
  ['Séismes, inondations, pannes électriques pouvant affecter les centres d'inspection et le datacenter', 'Earthquakes, floods, power outages that could affect inspection centers and the datacenter'],
  ['Erreurs de configuration des systèmes par le personnel IT pouvant créer des vulnérabilités', 'System configuration errors by IT staff that could create vulnerabilities'],

  ['Rapports DGSSI, CERT-MA, forums cybersécurité sectoriels', 'DGSSI, CERT-MA reports, sectoral cybersecurity forums'],
  ['Bulletins ANSSI, alertes CERT-MA, threat intelligence feeds', 'ANSSI bulletins, CERT-MA alerts, threat intelligence feeds'],
  ['Campagnes simulées internes, rapports sectoriels', 'Internal simulated campaigns, sectoral reports'],
  ['Analyse interne RH et audit de sécurité', 'Internal HR analysis and security audit'],
  ['Inventaire physique et rapports d'incidents internes', 'Physical inventory and internal incident reports'],
  ['Monitoring réseau, rapports ISP', 'Network monitoring, ISP reports'],
  ['Bulletins NVD, CVE, éditeurs logiciels', 'NVD, CVE, software vendor bulletins'],
  ['Rapports de sécurité Microsoft, Oracle, bulletins CERT', 'Microsoft, Oracle security reports, CERT bulletins'],
  ['Plans de continuité, études de risque site', 'Continuity plans, site risk studies'],
  ['Audits internes, rapports d'incidents', 'Internal audits, incident reports'],

  ['Contrôle des emails, détection phishing, segmentation réseau, réponse aux incidents', 'Email controls, phishing detection, network segmentation, incident response'],
  ['EDR déployé, sauvegardes offline, segmentation réseau, exercices de simulation', 'EDR deployed, offline backups, network segmentation, simulation exercises'],
  ['Formation phishing mensuelle, filtrage email, MFA obligatoire', 'Monthly phishing training, email filtering, mandatory MFA'],
  ['Contrôle des accès basé sur les rôles, séparation des tâches, monitoring', 'Role-based access control, separation of duties, monitoring'],
  ['Chiffrement des disques, MDM, effacement à distance, politique de verrouillage', 'Disk encryption, MDM, remote wipe, lock policy'],
  ['Protection DDoS Cloudflare, redondance internet, WAF', 'Cloudflare DDoS protection, internet redundancy, WAF'],
  ['Gestion des correctifs, veille vulnérabilités, tests de pénétration', 'Patch management, vulnerability monitoring, penetration testing'],
  ['Évaluation sécurité fournisseurs, clauses contractuelles, audits', 'Vendor security assessment, contractual clauses, audits'],
  ['PCA/PRA documentés et testés, redondance électrique, sites de secours', 'Documented and tested BCP/DRP, electrical redundancy, backup sites'],
  ['Procédures de changement, revues de configuration, formation IT', 'Change procedures, configuration reviews, IT training'],

  // Legal requirements
  ['Loi n°09-08 relative à la protection des personnes physiques à l'égard du traitement des données à caractère personnel', 'Law No. 09-08 on the protection of individuals with regard to the processing of personal data'],
  ['Loi n°05-20 relative à la cybersécurité au Maroc', 'Law No. 05-20 on cybersecurity in Morocco'],
  ['Décret n°2-09-165 portant application de la Loi 09-08', 'Decree No. 2-09-165 implementing Law 09-08'],
  ['Règlement Général sur la Protection des Données (RGPD)', 'General Data Protection Regulation (GDPR)'],
  ['ISO/IEC 17020:2012 - Exigences pour le fonctionnement de différents types d'organismes procédant à l'inspection', 'ISO/IEC 17020:2012 - Requirements for the operation of various types of bodies performing inspection'],
  ['Arrêté du Ministre du Transport relatif au contrôle technique des véhicules', 'Minister of Transport Order on vehicle technical inspection'],
  ['ISO 9001:2015 - Systèmes de management de la qualité', 'ISO 9001:2015 - Quality Management Systems'],
  ['ISO 45001:2018 - Systèmes de management de la santé et de la sécurité au travail', 'ISO 45001:2018 - Occupational Health and Safety Management Systems'],
  ['Dahir n°1-07-129 portant promulgation de la Loi 53-05 relative à l'échange électronique de données juridiques', 'Dahir No. 1-07-129 promulgating Law 53-05 on the electronic exchange of legal data'],
  ['Directive NIS2 (Network and Information Security) - applicable aux partenaires européens', 'NIS2 Directive (Network and Information Security) - applicable to European partners'],

  ['Traitement des données personnelles des clients pour les inspections techniques', 'Processing of customer personal data for technical inspections'],
  ['Obligations de sécurité des systèmes d'information au Maroc', 'Information system security obligations in Morocco'],
  ['Modalités de déclaration des traitements de données à la CNDP', 'Procedures for declaring data processing to the CNDP'],
  ['Protection des données des clients européens utilisant les services DEKRA Maroc', 'Protection of data for European clients using DEKRA Maroc services'],
  ['Accréditation DEKRA Maroc comme organisme d'inspection agréé', 'DEKRA Maroc accreditation as an approved inspection body'],
  ['Conformité réglementaire des activités d'inspection technique', 'Regulatory compliance of technical inspection activities'],
  ['Certification qualité des processus d'inspection et services', 'Quality certification of inspection processes and services'],
  ['Santé et sécurité des techniciens d'inspection et employés', 'Health and safety of inspection technicians and employees'],
  ['Signature électronique et archivage légal des rapports d'inspection', 'Electronic signature and legal archiving of inspection reports'],
  ['Sécurité des réseaux et systèmes pour les partenaires européens', 'Network and system security for European partners'],

  ['Registre CNDP n°A-123-2025, DPO désigné', 'CNDP register No. A-123-2025, DPO designated'],
  ['Politique sécurité SI validée par DG, RSSI nommé', 'IT security policy validated by DG, CISO appointed'],
  ['Déclaration CNDP enregistrée', 'CNDP declaration registered'],
  ['Clauses RGPD dans les contrats clients européens', 'GDPR clauses in European client contracts'],
  ['Certificat ISO 17020 Bureau Veritas valide jusqu\'en 2027', 'ISO 17020 Bureau Veritas certificate valid until 2027'],
  ['Agrément Ministère Transport en vigueur', 'Ministry of Transport accreditation in force'],
  ['Certificat ISO 9001:2015 en cours de renouvellement', 'ISO 9001:2015 certificate under renewal'],
  ['Certificat ISO 45001:2018 valide', 'ISO 45001:2018 certificate valid'],
  ['Procédure d\'archivage électronique déployée', 'Electronic archiving procedure deployed'],
  ['Clause NIS2 intégrée aux contrats partenaires UE', 'NIS2 clause integrated into EU partner contracts'],

  // BCP
  ['Plan de Reprise d'Activité SIVI', 'SIVI Disaster Recovery Plan'],
  ['Plan de Continuité - Panne Réseau', 'Business Continuity Plan - Network Failure'],
  ['Plan de Gestion de Crise Cybersécurité', 'Cybersecurity Crisis Management Plan'],
  ['Plan de Continuité - Indisponibilité Datacenter', 'Business Continuity Plan - Datacenter Unavailability'],
  ['Plan de Continuité - Pandémie', 'Business Continuity Plan - Pandemic'],

  ['Gestion des inspections techniques véhicules (SIVI), émission des procès-verbaux', 'Vehicle technical inspection management (SIVI), report issuance'],
  ['Accès Internet, VPN, messagerie, portail client', 'Internet access, VPN, email, client portal'],
  ['Opérations IT, communications internes/externes, monitoring', 'IT operations, internal/external communications, monitoring'],
  ['Accès aux applications critiques (SIVI, Oracle, M365)', 'Access to critical applications (SIVI, Oracle, M365)'],
  ['Ensemble des opérations de DEKRA Maroc', 'All DEKRA Maroc operations'],

  ['Serveur secondaire préconfiguré en hot standby, synchronisation Oracle DataGuard', 'Pre-configured secondary server in hot standby, Oracle DataGuard synchronization'],
  ['Basculement MPLS vers 4G/5G, activation liaisons de secours Maroc Telecom', 'MPLS failover to 4G/5G, activation of Maroc Telecom backup links'],
  ['Activation équipe de crise, communication dirigeants, isolement systèmes impactés', 'Crisis team activation, leadership communication, isolation of impacted systems'],
  ['Activation site secondaire Rabat, restauration depuis sauvegarde Veeam', 'Rabat secondary site activation, restore from Veeam backup'],
  ['Télétravail généralisé, accès VPN renforcé, suspension des inspections physiques si nécessaire', 'Generalized remote work, reinforced VPN access, suspension of physical inspections if needed'],

  ['Test réussi - basculement SIVI en 2h20 (objectif 4h)', 'Test passed - SIVI failover in 2h20 (4h target)'],
  ['Test partiel - reconnexion en 45min, quelques sites secondaires non testés', 'Partial test - reconnection in 45 min, some secondary sites not tested'],
  ['Exercice de simulation effectué, temps de réponse équipe crise satisfaisant', 'Simulation exercise completed, crisis team response time satisfactory'],
  ['Test réussi - RPO atteint, RTO légèrement dépassé (6h vs 4h objectif)', 'Test passed - RPO achieved, RTO slightly exceeded (6h vs 4h target)'],
  ['Test théorique uniquement - test réel planifié Q3 2026', 'Theoretical test only - real test planned Q3 2026'],

  ['Améliorer le script de basculement automatique', 'Improve automatic failover script'],
  ['Tester tous les sites secondaires lors du prochain exercice', 'Test all secondary sites during the next exercise'],
  ['Améliorer les procédures de communication de crise', 'Improve crisis communication procedures'],
  ['Optimiser le processus de restauration pour atteindre l'objectif RTO', 'Optimize the restoration process to meet RTO target'],
  ['Planifier un test grandeur nature', 'Plan a full-scale test'],

  ['Serveur secondaire, Oracle DataGuard, sauvegardes Veeam', 'Secondary server, Oracle DataGuard, Veeam backups'],
  ['Liens 4G/5G Maroc Telecom, IAM comme backup', '4G/5G Maroc Telecom links, IAM as backup'],
  ['Équipements de communication de crise, accès VPN hors-bande', 'Crisis communication equipment, out-of-band VPN access'],
  ['Site secondaire Rabat, Veeam Cloud Connect', 'Rabat secondary site, Veeam Cloud Connect'],
  ['VPN renforcé, solutions collaboration cloud', 'Reinforced VPN, cloud collaboration solutions'],

  // Management reviews
  ['Revue de Direction SMSI - Q1 2026', 'ISMS Management Review - Q1 2026'],
  ['Revue de Direction SMSI - Q3 2025', 'ISMS Management Review - Q3 2025'],
  ['Revue de Direction SMSI - Annuelle 2025', 'ISMS Management Review - Annual 2025'],
  ['Revue de Direction SMSI - Q1 2025', 'ISMS Management Review - Q1 2025'],

  ['Mohammed Amine Benali (DG), Youssef Tazi (DSI), Fatima Zahra Alaoui (RSSI), Omar Chraibi (QHSE), Leila Bennani (DRH), Amina Kadiri (Juridique), Karim Mansouri (Audit)', 'Mohammed Amine Benali (CEO), Youssef Tazi (CIO), Fatima Zahra Alaoui (CISO), Omar Chraibi (QHSE), Leila Bennani (HR), Amina Kadiri (Legal), Karim Mansouri (Audit)'],
  ['Mohammed Amine Benali (DG), Youssef Tazi (DSI), Fatima Zahra Alaoui (RSSI), Omar Chraibi (QHSE), Karim Mansouri (Audit)', 'Mohammed Amine Benali (CEO), Youssef Tazi (CIO), Fatima Zahra Alaoui (CISO), Omar Chraibi (QHSE), Karim Mansouri (Audit)'],

  ['Résultats des audits, statut des risques, performance des contrôles, avancement des objectifs, incidents de sécurité, retours parties intéressées', 'Audit results, risk status, control performance, objective progress, security incidents, interested party feedback'],
  ['Décisions sur les ressources, actions correctives prioritaires, mise à jour des objectifs SMSI, décision sur la certification ISO 27001', 'Decisions on resources, priority corrective actions, ISMS objectives update, decision on ISO 27001 certification'],
  ['Lancement officiel du projet de certification ISO 27001:2022, allocation budget 500k MAD, nomination RSSI', 'Official launch of ISO 27001:2022 certification project, 500k MAD budget allocation, CISO appointment'],
  ['Approbation du plan de traitement des risques, validation des politiques SMSI v2.0', 'Risk treatment plan approval, ISMS policies v2.0 validation'],

  ['Engager Bureau Veritas pour l\'audit de certification Q4 2026', 'Engage Bureau Veritas for Q4 2026 certification audit'],
  ['Finaliser le déploiement SIEM avant fin Q3 2026', 'Complete SIEM deployment before end of Q3 2026'],
  ['Réaliser l\'audit de pré-certification interne avant septembre 2026', 'Conduct internal pre-certification audit before September 2026'],
  ['Compléter le déploiement MFA sur tous les accès critiques', 'Complete MFA deployment on all critical access points'],
  ['Approuver le budget formation sécurité 2026', 'Approve 2026 security training budget'],
  ['Valider la politique de gestion des fournisseurs', 'Validate vendor management policy'],
  ['Approuver le plan de traitement des risques révisé', 'Approve revised risk treatment plan'],
  ['Lancer l\'appel d\'offre pour le SIEM', 'Launch RFP for SIEM solution'],

  // Communications
  ['Rapport mensuel sécurité SMSI', 'Monthly ISMS Security Report'],
  ['Bulletin de sensibilisation sécurité', 'Security Awareness Bulletin'],
  ['Rapport annuel SMSI à la Direction Générale', 'Annual ISMS Report to General Management'],
  ['Communication incidents de sécurité', 'Security Incident Communication'],
  ['Notification de fuite de données à la CNDP', 'Data Breach Notification to CNDP'],
  ['Communication résultats audits internes', 'Internal Audit Results Communication'],
  ['Revue trimestrielle des fournisseurs', 'Quarterly Vendor Review'],
  ['Sensibilisation mensuelle au phishing', 'Monthly Phishing Awareness'],
  ['Communication changements majeurs SMSI', 'Major ISMS Changes Communication'],
  ['Rapport de conformité aux clients entreprise', 'Compliance Report to Enterprise Clients'],

  ['Direction Générale, Comité de Direction', 'General Management, Executive Committee'],
  ['Ensemble des employés DEKRA Maroc', 'All DEKRA Maroc employees'],
  ['Direction Générale', 'General Management'],
  ['Équipe de réponse aux incidents, Management', 'Incident response team, Management'],
  ['CNDP (Commission Nationale de contrôle de la protection des Données Personnelles)', 'CNDP (National Commission for Personal Data Protection Control)'],
  ['Management, Équipes métier concernées', 'Management, relevant business teams'],
  ['Direction Achats, Direction Générale', 'Procurement Management, General Management'],
  ['Ensemble du personnel', 'All staff'],
  ['Direction Générale, Responsables de département', 'General Management, Department Heads'],
  ['Clients entreprise, partenaires contractuels', 'Enterprise clients, contractual partners'],

  ['Tableau de bord KPI sécurité, alertes incidents, statut contrôles', 'Security KPI dashboard, incident alerts, control status'],
  ['Newsletter sécurité mensuelle sur l\'intranet', 'Monthly security newsletter on the intranet'],
  ['Rapport annuel de performance du SMSI', 'Annual ISMS performance report'],
  ['Notification immédiate en cas d\'incident confirmé', 'Immediate notification upon confirmed incident'],
  ['Rapport de violation obligatoire sous 72h conformément à la Loi 09-08', 'Mandatory breach report within 72h per Law 09-08'],
  ['Résumé exécutif des findings et actions correctives', 'Executive summary of findings and corrective actions'],
  ['Rapport de performance sécurité des fournisseurs', 'Vendor security performance report'],
  ['Simulation de phishing avec rapport de résultats', 'Phishing simulation with results report'],
  ['Communication via email, réunion d\'information', 'Communication via email, information meeting'],
  ['Rapport de conformité sécurité certifié SMSI', 'ISMS-certified security compliance report'],

  // Improvements
  ['Déployer une solution SIEM pour la détection des incidents', 'Deploy SIEM Solution for Incident Detection'],
  ['Implémenter le MFA sur tous les accès critiques', 'Implement MFA on All Critical Access Points'],
  ['Renforcer la sécurité physique des centres d\'inspection', 'Strengthen Physical Security at Inspection Centers'],
  ['Automatiser les scans de vulnérabilités', 'Automate Vulnerability Scanning'],
  ['Mettre en place un programme DLP (Data Loss Prevention)', 'Implement a DLP (Data Loss Prevention) Program'],
  ['Créer un SOC (Security Operations Center) interne', 'Establish an Internal SOC (Security Operations Center)'],
  ['Déployer un programme de Bug Bounty', 'Deploy a Bug Bounty Program'],
  ['Améliorer la gestion des identités (IAM)', 'Improve Identity and Access Management (IAM)'],
  ['Former les développeurs à la sécurité applicative', 'Train Developers in Application Security'],

  ['Absence de visibilité centralisée sur les événements de sécurité', 'Lack of centralized visibility on security events'],
  ['MFA non déployé sur plusieurs systèmes critiques (SIVI, Oracle, VPN)', 'MFA not deployed on several critical systems (SIVI, Oracle, VPN)'],
  ['Contrôles d\'accès physiques insuffisants dans certains centres régionaux', 'Insufficient physical access controls at some regional centers'],
  ['Processus de scan de vulnérabilités manuel et irrégulier', 'Manual and irregular vulnerability scanning process'],
  ['Risque de fuite de données sensibles via email, USB ou cloud personnel', 'Risk of sensitive data leakage via email, USB or personal cloud'],
  ['Manque de capacité de détection et réponse aux incidents en temps réel', 'Lack of real-time incident detection and response capability'],
  ['Identifier les vulnérabilités non découvertes par les tests internes', 'Identify vulnerabilities not discovered by internal testing'],
  ['Gestion des identités fragmentée entre plusieurs annuaires et applications', 'Fragmented identity management across multiple directories and applications'],
  ['Vulnérabilités applicatives identifiées lors du dernier pentest', 'Application vulnerabilities identified during the last pentest'],

  ['Réduction significative du MTTD (Mean Time to Detect)', 'Significant reduction in MTTD (Mean Time to Detect)'],
  ['Élimination des accès non autorisés via authentification renforcée', 'Elimination of unauthorized access through enhanced authentication'],
  ['Réduction des risques d\'intrusion physique dans les zones sensibles', 'Reduction of physical intrusion risk in sensitive areas'],
  ['Détection précoce des vulnérabilités avant exploitation', 'Early vulnerability detection before exploitation'],
  ['Prévention des fuites de données confidentielles', 'Prevention of confidential data leakage'],
  ['Amélioration de la capacité de réponse aux incidents', 'Improved incident response capability'],
  ['Amélioration de la posture sécurité globale', 'Improved overall security posture'],
  ['Simplification de la gestion des accès et amélioration de l\'audit', 'Simplified access management and improved auditability'],
  ['Réduction des risques de sécurité applicative', 'Reduced application security risks'],

  // Evidence
  ['Rapport d\'Audit Interne SMSI Q1 2026', 'Internal ISMS Audit Report Q1 2026'],
  ['Politique de Sécurité de l\'Information v3.0', 'Information Security Policy v3.0'],
  ['Résultats Tests de Phishing Simulés - Mai 2026', 'Simulated Phishing Test Results - May 2026'],
  ['Certificat ISO 17020:2012 Bureau Veritas', 'ISO 17020:2012 Bureau Veritas Certificate'],
  ['Rapport de Test de Pénétration Externe 2025', 'External Penetration Test Report 2025'],
  ['Registre de Traitement des Données Personnelles CNDP', 'CNDP Personal Data Processing Register'],
  ['Logs Active Directory - Revue des accès Q2 2026', 'Active Directory Logs - Q2 2026 Access Review'],
  ['Contrat de Confidentialité Fournisseur OVHcloud', 'OVHcloud Vendor Confidentiality Agreement'],
  ['Procès-verbal Revue de Direction Q1 2026', 'Q1 2026 Management Review Minutes'],
  ['Rapport de Scan Vulnérabilités - Nessus Juin 2026', 'Vulnerability Scan Report - Nessus June 2026'],
  ['Formation Sécurité Complétée - Équipe Comptabilité', 'Security Training Completed - Accounting Team'],
  ['Plan de Continuité d\'Activité SIVI - Test Q1 2026', 'SIVI Business Continuity Plan - Q1 2026 Test'],

  ['Rapport complet de l\'audit interne SMSI couvrant les clauses 4 à 10 de l\'ISO 27001:2022', 'Complete internal ISMS audit report covering clauses 4 to 10 of ISO 27001:2022'],
  ['Document de politique officielle approuvé par la Direction Générale', 'Official policy document approved by General Management'],
  ['Rapport statistique des tests de phishing simulés envoyés à 450 employés', 'Statistical report of simulated phishing tests sent to 450 employees'],
  ['Certificat d\'accréditation ISO/IEC 17020 en cours de validité', 'Valid ISO/IEC 17020 accreditation certificate'],
  ['Rapport de pentest externe réalisé par un cabinet spécialisé', 'External pentest report conducted by a specialized firm'],
  ['Registre officiel des traitements de données soumis à la CNDP', 'Official data processing register submitted to CNDP'],
  ['Export des logs d\'audit Active Directory pour la période Q2 2026', 'Active Directory audit log export for Q2 2026 period'],
  ['Accord de traitement des données et clauses de confidentialité OVHcloud', 'OVHcloud data processing agreement and confidentiality clauses'],
  ['Compte rendu officiel de la revue de direction SMSI du 15 mars 2026', 'Official minutes of the ISMS management review of March 15, 2026'],
  ['Rapport de scan de vulnérabilités Nessus Professional sur l\'infrastructure', 'Nessus Professional vulnerability scan report on the infrastructure'],
  ['Attestations de complétion de la formation sécurité de l\'équipe comptabilité', 'Security training completion certificates for the accounting team'],
  ['Documentation du test de reprise SIVI incluant les métriques RTO/RPO', 'SIVI recovery test documentation including RTO/RPO metrics'],

  ['audit, contrôle', 'audit, control'],
  ['politique, smsi', 'policy, isms'],
  ['phishing, sensibilisation, formation', 'phishing, awareness, training'],
  ['certificat, accréditation, iso17020', 'certificate, accreditation, iso17020'],
  ['pentest, vulnérabilités, sécurité', 'pentest, vulnerabilities, security'],
  ['cndp, conformité, données personnelles', 'cndp, compliance, personal data'],
  ['logs, audit, active directory', 'logs, audit, active directory'],
  ['fournisseur, contrat, confidentialité', 'vendor, contract, confidentiality'],
  ['revue direction, gouvernance', 'management review, governance'],
  ['vulnérabilités, scan, infrastructure', 'vulnerabilities, scan, infrastructure'],
  ['formation, complétion, certification', 'training, completion, certification'],
  ['bcp, pra, continuité', 'bcp, dra, continuity'],

  ['POL-SMSI-001-v3.0.pdf', 'POL-ISMS-001-v3.0.pdf'],
  ['RPT-AUDIT-INTERNE-Q1-2026.pdf', 'RPT-INTERNAL-AUDIT-Q1-2026.pdf'],
  ['RPT-PHISHING-MAI-2026.xlsx', 'RPT-PHISHING-MAY-2026.xlsx'],
  ['CERT-ISO17020-BV-2024.pdf', 'CERT-ISO17020-BV-2024.pdf'],
  ['RPT-PENTEST-EXT-2025.pdf', 'RPT-PENTEST-EXT-2025.pdf'],
  ['REG-CNDP-2025.pdf', 'REG-CNDP-2025.pdf'],
  ['LOG-AD-Q2-2026.zip', 'LOG-AD-Q2-2026.zip'],
  ['DPA-OVHCLOUD-2025.pdf', 'DPA-OVHCLOUD-2025.pdf'],
  ['PV-REVUE-DIR-Q1-2026.pdf', 'MOM-MGMT-REVIEW-Q1-2026.pdf'],
  ['RPT-NESSUS-JUN-2026.pdf', 'RPT-NESSUS-JUN-2026.pdf'],
  ['FORM-SECU-COMPTA-2026.pdf', 'FORM-SECU-ACCOUNTING-2026.pdf'],
  ['BCP-SIVI-TEST-Q1-2026.pdf', 'BCP-SIVI-TEST-Q1-2026.pdf'],

  // Vulnerabilities
  ['Vulnérabilité critique Fortinet FortiOS', 'Critical Fortinet FortiOS Vulnerability'],
  ['Vulnérabilité OpenSSH RegreSSHion', 'OpenSSH RegreSSHion Vulnerability'],
  ['Vulnérabilité Microsoft Outlook NTLM', 'Microsoft Outlook NTLM Vulnerability'],
  ['VPN SSL DEKRA exposé à internet avec firmware obsolète', 'DEKRA SSL VPN exposed to internet with outdated firmware'],
  ['Exécution de code distant sur serveurs OpenSSH non patchés', 'Remote code execution on unpatched OpenSSH servers'],
  ['Fuite de hash NTLM via emails malformés dans Outlook', 'NTLM hash leak via malformed emails in Outlook'],
  ['HTTP/2 Rapid Reset - Risque DDoS sur le portail web', 'HTTP/2 Rapid Reset - DDoS Risk on Web Portal'],
  ['Vulnérabilité Confluence Data Center', 'Confluence Data Center Vulnerability'],
  ['Injection SQL dans l\'application SIVI Web', 'SQL Injection in SIVI Web Application'],
  ['TLS 1.0/1.1 activé sur serveurs legacy', 'TLS 1.0/1.1 Enabled on Legacy Servers'],
  ['Politique de mots de passe faible sur VPN', 'Weak Password Policy on VPN'],
  ['Apache HTTP Server - Path Traversal', 'Apache HTTP Server - Path Traversal'],

  ['Faille d\'authentification dans FortiOS permettant à un attaquant distant d\'accéder au système de management VPN', 'Authentication bypass in FortiOS allowing remote attacker to access VPN management system'],
  ['Race condition dans OpenSSH\'s server (sshd) permettant l\'exécution de code non authentifié', 'Race condition in OpenSSH server (sshd) allowing unauthenticated code execution'],
  ['Vulnérabilité permettant le vol de hash NTLM via un email spécialement conçu, sans interaction utilisateur', 'Vulnerability allowing NTLM hash theft via a specially crafted email, without user interaction'],
  ['L\'attaque Rapid Reset exploite la gestion des streams HTTP/2 pour saturer et paralyser le serveur web', 'The Rapid Reset attack exploits HTTP/2 stream management to overwhelm and paralyze the web server'],
  ['Exécution de code à distance (RCE) sur Confluence Server - exploitation active observée', 'Remote code execution (RCE) on Confluence Server - active exploitation observed'],
  ['Injection SQL identifiée lors du pentest dans le module de recherche de l\'application SIVI web', 'SQL injection identified during pentest in the search module of the SIVI web application'],
  ['Utilisation de protocoles TLS obsolètes (1.0 et 1.1) vulnérables à des attaques BEAST et POODLE', 'Use of obsolete TLS protocols (1.0 and 1.1) vulnerable to BEAST and POODLE attacks'],
  ['Politique de complexité insuffisante permettant des mots de passe de 6 caractères sur le VPN Cisco', 'Insufficient complexity policy allowing 6-character passwords on the Cisco VPN'],
  ['Vulnérabilité de traversée de répertoire permettant l\'accès à des fichiers sensibles sur le serveur Apache', 'Directory traversal vulnerability allowing access to sensitive files on the Apache server'],

  ['Mise à jour firmware FortiOS vers version 7.4.4+', 'Update FortiOS firmware to version 7.4.4+'],
  ['Application du patch de sécurité OpenSSH 9.8+', 'Apply OpenSSH 9.8+ security patch'],
  ['Déploiement du patch MS24-009 via WSUS', 'Deploy patch MS24-009 via WSUS'],
  ['Mise à jour du serveur web, activation protection DDoS', 'Update web server, enable DDoS protection'],
  ['Migration vers Confluence Cloud ou patch 8.5.4+', 'Migrate to Confluence Cloud or patch 8.5.4+'],
  ['Correction du code SQL, déploiement WAF, validation par pentest', 'Fix SQL code, deploy WAF, validate via pentest'],
  ['Désactivation TLS 1.0/1.1, migration vers TLS 1.3', 'Disable TLS 1.0/1.1, migrate to TLS 1.3'],
  ['Renforcement politique MDP VPN (min 12 chars, complexité)', 'Strengthen VPN password policy (min 12 chars, complexity)'],
  ['Application patch Apache 2.4.59, audit configurations', 'Apply Apache 2.4.59 patch, audit configurations'],

  ['Firmware FortiOS obsolète', 'Outdated FortiOS firmware'],
  ['Système non patché', 'Unpatched system'],
  ['Client Outlook non mis à jour', 'Outlook client not updated'],
  ['Serveur web non patché', 'Web server not patched'],
  ['Instance Confluence non patchée', 'Unpatched Confluence instance'],
  ['Validation d\'entrées insuffisante dans le code SIVI', 'Insufficient input validation in SIVI code'],
  ['Configuration TLS non mise à jour', 'TLS configuration not updated'],
  ['Politique MDP insuffisante', 'Insufficient password policy'],
  ['Configuration Apache non durcie', 'Apache configuration not hardened'],

  ['VPN SSL (Fortinet FortiGate)', 'SSL VPN (Fortinet FortiGate)'],
  ['Serveurs Linux Ubuntu 22.04', 'Linux Ubuntu 22.04 Servers'],
  ['Clients Microsoft Outlook 2019', 'Microsoft Outlook 2019 Clients'],
  ['Serveur web Apache - Portail client', 'Apache Web Server - Client Portal'],
  ['Serveur Confluence interne', 'Internal Confluence Server'],
  ['Application web SIVI', 'SIVI Web Application'],
  ['Serveurs web et API legacy', 'Legacy Web and API Servers'],
  ['Portail VPN Cisco AnyConnect', 'Cisco AnyConnect VPN Portal'],
  ['Serveur Apache 2.4.51', 'Apache Server 2.4.51'],

  ['Pentest externe', 'External pentest'],
  ['Scanner Nessus interne', 'Internal Nessus scanner'],
  ['Bulletin sécurité Microsoft', 'Microsoft security bulletin'],
  ['Monitoring réseau interne', 'Internal network monitoring'],
  ['Rapport NVD/CISA KEV', 'NVD/CISA KEV report'],
  ['Pentest interne DEKRA', 'DEKRA internal pentest'],
  ['Analyse configuration interne', 'Internal configuration analysis'],
  ['Audit de configuration DSI', 'IT Department configuration audit'],

  // Notifications
  ['Audit de certification ISO 27001 planifié', 'ISO 27001 Certification Audit Scheduled'],
  ['Vulnérabilité Critique Détectée', 'Critical Vulnerability Detected'],
  ['Formation Phishing - Taux d\'échec Élevé', 'Phishing Training - High Failure Rate'],
  ['Revue de Direction SMSI - Rappel', 'ISMS Management Review - Reminder'],
  ['Non-conformité Audit Interne', 'Internal Audit Nonconformity'],
  ['Incident de Sécurité Résolu', 'Security Incident Resolved'],
  ['Mise à jour Politique SMSI', 'ISMS Policy Update'],
  ['Certificat SSL Expire Bientôt', 'SSL Certificate Expiring Soon'],

  ['L\'audit de certification ISO 27001:2022 avec Bureau Veritas est planifié pour le 15 novembre 2026. Préparez les preuves et la documentation.', 'The ISO 27001:2022 certification audit with Bureau Veritas is scheduled for November 15, 2026. Prepare evidence and documentation.'],
  ['CVE-2024-21762 (CVSS 9.8) détectée sur les équipements FortiGate. Mise à jour urgente requise dans les 24h.', 'CVE-2024-21762 (CVSS 9.8) detected on FortiGate devices. Urgent update required within 24h.'],
  ['23% des employés ont cliqué sur le dernier test de phishing simulé. Le seuil acceptable est 10%. Action corrective requise.', '23% of employees clicked on the latest simulated phishing test. Acceptable threshold is 10%. Corrective action required.'],
  ['La revue de direction SMSI Q1 2026 est prévue le 15 mars. Préparez vos rapports KPI et le statut des actions ouvertes.', 'The Q1 2026 ISMS management review is scheduled for March 15. Prepare your KPI reports and open action status.'],
  ['L\'audit interne a identifié 3 non-conformités mineures. Merci de préparer les plans d\'action corrective avant le 30 juin 2026.', 'The internal audit identified 3 minor nonconformities. Please prepare corrective action plans before June 30, 2026.'],
  ['L\'incident de phishing du 5 juin 2026 a été résolu. Aucune donnée compromise. Rapport d\'incident disponible.', 'The phishing incident of June 5, 2026 has been resolved. No data was compromised. Incident report available.'],
  ['La Politique de Sécurité de l\'Information a été mise à jour en version 3.0. Veuillez en prendre connaissance et signer l\'accusé de réception.', 'The Information Security Policy has been updated to version 3.0. Please review it and sign the acknowledgment.'],
  ['Le certificat SSL du portail client expire dans 30 jours. Procéder au renouvellement avant le 10 juillet 2026.', 'The SSL certificate for the client portal expires in 30 days. Proceed with renewal before July 10, 2026.'],

  // Settings
  ['certificationTarget', 'certificationTarget'],
  ['Q4 2026', 'Q4 2026'],
  ['reviewFrequency', 'reviewFrequency'],
  ['Annuellement', 'Annually'],

  // Remaining general French
  ['Département', 'Department'],
  ['département', 'department'],
  ['réponse', 'response'],
  ['sensibilisation', 'awareness'],
  ['fournisseurs', 'vendors'],
  ['fournisseur', 'vendor'],
  ['conformité', 'compliance'],
  ['sécurité', 'security'],
  ['données', 'data'],
  ['système', 'system'],
  ['systèmes', 'systems'],
  ['formation', 'training'],
  ['politique', 'policy'],
  ['politiques', 'policies'],
  ['audit', 'audit'],
  ['audits', 'audits'],
  ['risque', 'risk'],
  ['risques', 'risks'],
  ['contrôles', 'controls'],
  ['contrôle', 'control'],
  ['accès', 'access'],
  ['réseau', 'network'],
  ['réseaux', 'networks'],
  ['infrastructure', 'infrastructure'],
  ['Direction', 'Management'],
  ['direction', 'management'],
  ['incidents', 'incidents'],
  ['incident', 'incident'],
  ['vulnérabilités', 'vulnerabilities'],
  ['vulnérabilité', 'vulnerability'],
  ['objectifs', 'objectives'],
  ['objectif', 'objective'],
  ['opérations', 'operations'],
  ['opération', 'operation'],
  ['ressources', 'resources'],
  ['ressource', 'resource'],
  ['documentation', 'documentation'],
  ['procédure', 'procedure'],
  ['procédures', 'procedures'],
  ['employés', 'employees'],
  ['employé', 'employee'],
  ['personnel', 'staff'],
  ['actifs', 'assets'],
  ['actif', 'asset'],
  ['tiers', 'third-party'],
  ['prestataire', 'service provider'],
  ['prestataires', 'service providers'],
  ['chiffrement', 'encryption'],
  ['protection', 'protection'],
  ['surveillance', 'monitoring'],
  ['disponibilité', 'availability'],
  ['continuité', 'continuity'],
  ['intégrité', 'integrity'],
  ['confidentialité', 'confidentiality'],
  ['gestion', 'management'],
  ['déploiement', 'deployment'],
  ['déployé', 'deployed'],
  ['amélioration', 'improvement'],
  ['améliorer', 'improve'],
  ['analyse', 'analysis'],
  ['évaluation', 'assessment'],
  ['rapport', 'report'],
  ['rapports', 'reports'],
  ['mise à jour', 'update'],
  ['mises à jour', 'updates'],
  ['obligations', 'obligations'],
  ['exigences', 'requirements'],
  ['identification', 'identification'],
  ['processus', 'process'],
  ['services', 'services'],
  ['service', 'service'],
  ['certification', 'certification'],
  ['performances', 'performance'],
  ['performance', 'performance'],
  ['maintenance', 'maintenance'],
  ['sauvegardes', 'backups'],
  ['sauvegarde', 'backup'],
  ['restauration', 'recovery'],
  ['communication', 'communication'],
  ['communications', 'communications'],
  ['planification', 'planning'],
  ['compétences', 'skills'],
  ['compétence', 'skill'],
  ['information', 'information'],
  ['informations', 'information'],
  ['organisation', 'organization'],
  ['équipe', 'team'],
  ['équipes', 'teams'],
];

for (const [fr, en] of r) {
  c = c.split(fr).join(en);
}

fs.writeFileSync('prisma/seed.ts', c, 'utf8');
console.log('Done');
